### ISSUE TITLE
bukkit/spigot API is inside the final jar on spigotmc

### ISSUE THREAD

**Issue by Janmm14** [BlakeStevenson/ShulkerCore#1]
Please remove the copy of bukkit/spigot api from the jar file you upload. This increases the file size unneccessarily and significantly and might create compatibility problems.

**Comment by BlakeStevenson** [comment]
I’m not working on this plugin anymore, if you need something similar just go ahead and use EssentialsX.

**Comment by Janmm14** [comment]
I don't need it myself, I was just going through a spigotmc scan.
